### ISSUE TITLE
I think I finally got one lol

### ISSUE THREAD

**Issue by jargoman** [pmarches/jStellarAPI#19]
RippleBinarySerializer method readAmount line 129
You forgot to add the sign to BigDecimal fractionalValue
BigInteger biMagnitude = BigInteger.valueOf(longMagnitude);
should be...
BigInteger biMagnitude = BigInteger.valueOf(longMagnitude * sign);

or if you'd rather 
if (sign<0) {
     fractionalValue.negate();
}

**Comment by nybbs2003** [comment]
should't this be closed as it is solved?

**Comment by pmarches** [comment]
Indeed, I thought I had.
